In [2]:
import numpy as np
from matplotlib import pyplot as plt

In [10]:
#2D case


t = 1
U = 1

H = np.array([[U,-t,-t,-0],[-t,0,0,-t],[-t,0,0,-t],[0,-t,-t,U]])
print(H)
eigE, eigV = np.linalg.eigh(H)

[[ 1 -1 -1  0]
 [-1  0  0 -1]
 [-1  0  0 -1]
 [ 0 -1 -1  1]]


In [11]:
def binom(N,k):
    return np.math.factorial(N)/(np.math.factorial(k)*np.math.factorial(N-k))

In [21]:
Nu = 1
Nd = 1
N = 2
dim = binom(N,Nu)*binom(N,Nd)
vac = np.zeros(N)

basis = np.array([])

for i in range(int(dim)):
    print(i)

0
1
2
3
[0. 0.]
[]


In [27]:
#Full Hamiltonian

N = 2
L = 2

for i in range(1,L+2):
    print(i)
    print(bin(L,i))

1


TypeError: bin() takes exactly one argument (2 given)